[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/on-inner-desires"
  to = "/playground/on-inner-desires/"
  status = 301

[[redirects]]
  from = "/how-i-work"
  to = "/"
  status = 301

[[redirects]]
  from = "http://www.francescoimola.com/"
  to = "https://francescoimola.com"
  status = 301

[[redirects]]
  from = "https://www.francescoimola.com/"
  to = "https://francescoimola.com"
  status = 301
